name: 'museum_dbt'
version: '1.0.0'

profile: 'museum_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

<<<<<<< HEAD
=======

>>>>>>> feature/dbt-silver-layer
models:
  museum_dbt:
    silver:
      +schema: silver
<<<<<<< HEAD
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
=======
    # gold:
    #   +schema: gold 
>>>>>>> feature/dbt-silver-layer
