-- ============================================================
-- Q09 · fct_sales Grain & Surrogate Key Audit  ← SINGLE TABLE
-- Joins : fct_sales only  (no dimension joins needed)
-- Difficulty : High
-- ============================================================
-- PURPOSE
--   Verify the deduplication logic in fct_sales is working correctly.
--   The model uses ROW_NUMBER() partitioned by (work_id, size_id) and
--   a surrogate key generated by dbt_utils.generate_surrogate_key.
--   This audit confirms:
--     1. No duplicate (work_id, size_id) pairs exist
--     2. Every sales_key is unique (surrogate key integrity)
--     3. No NULL values on required FK columns
--     4. discount_amount = regular_price - sale_price (within rounding)
--
-- EXPECTED RESULTS FOR A CLEAN MODEL
--   duplicate_work_size_pairs  → 0
--   duplicate_sales_keys       → 0
--   null_work_id               → 0
--   null_size_id               → 0
--   null_artist_id             → 0  (or explains unmapped artists)
--   discount_calc_mismatches   → 0
-- ============================================================

SELECT
    -- Grain check: (work_id, size_id) must be unique
    SUM(CASE WHEN cnt > 1 THEN 1 ELSE 0 END)       AS duplicate_work_size_pairs,

    -- Surrogate key uniqueness
    SUM(CASE WHEN key_cnt > 1 THEN 1 ELSE 0 END)   AS duplicate_sales_keys,

    -- Null FK checks
    SUM(null_work)                                  AS null_work_id,
    SUM(null_size)                                  AS null_size_id,
    SUM(null_artist)                                AS null_artist_id,
    SUM(null_museum)                                AS null_museum_id,

    -- Derived column accuracy
    SUM(discount_mismatch)                          AS discount_calc_mismatches,

    -- Overall row count
    SUM(total_rows)                                 AS total_fact_rows
FROM (
    SELECT
        -- Grain duplicates
        COUNT(*) OVER (PARTITION BY work_id, size_id)           AS cnt,
        -- Key duplicates
        COUNT(*) OVER (PARTITION BY sales_key)                  AS key_cnt,
        -- Null checks (1 = bad row)
        CASE WHEN work_id   IS NULL THEN 1 ELSE 0 END           AS null_work,
        CASE WHEN size_id   IS NULL THEN 1 ELSE 0 END           AS null_size,
        CASE WHEN artist_id IS NULL THEN 1 ELSE 0 END           AS null_artist,
        CASE WHEN museum_id IS NULL THEN 1 ELSE 0 END           AS null_museum,
        -- Discount derivation: allow ±0.02 rounding tolerance
        CASE
            WHEN ABS(
                    COALESCE(discount_amount, 0)
                    - COALESCE(regular_price - sale_price, 0)
                 ) > 0.02
            THEN 1 ELSE 0
        END                                                     AS discount_mismatch,
        1                                                       AS total_rows
    FROM gold.fct_sales
) sub;